# 480 hints are all supressed with the following ignores.
- ignore: {name: Redundant bracket} 
- ignore: {name: Redundant if} 
- ignore: {name: Redundant guard} 
- ignore: {name: Redundant lambda} 
- ignore: {name: Redundant $} 
- ignore: {name: Redundant <$>} 
- ignore: {name: Redundant bang pattern} 
- ignore: {name: Redundant flip} 
- ignore: {name: Redundant return} 
- ignore: {name: Use camelCase} 
- ignore: {name: Use newtype instead of data} 
- ignore: {name: Use section} 
- ignore: {name: Use gets} 
- ignore: {name: Use guards} 
- ignore: {name: Use maybe} 
- ignore: {name: Use fold} 
- ignore: {name: Use map} 
- ignore: {name: Use map once} 
- ignore: {name: Use mapMaybe} 
- ignore: {name: Use concatMap} 
- ignore: {name: Use infix} 
- ignore: {name: Use elem} 
- ignore: {name: Use notElem} 
- ignore: {name: Use <$>} 
- ignore: {name: Use <$} 
- ignore: {name: Use $>} 
- ignore: {name: Use if} 
- ignore: {name: Use /=} 
- ignore: {name: Use ++} 
- ignore: {name: Use const} 
- ignore: {name: Use void} 
- ignore: {name: Use first} 
- ignore: {name: Use second} 
- ignore: {name: Use all} 
- ignore: {name: Use tuple-section} 
- ignore: {name: Use record patterns} 
- ignore: {name: Eta reduce} 
- ignore: {name: Unused LANGUAGE pragma} 
- ignore: {name: Fix pragma markup} 
- ignore: {name: Functor law} 
- ignore: {name: Avoid lambda} 
- ignore: {name: Move brackets to avoid $} 