# Warnings currently triggered by your code
- ignore: {name: "Avoid lambda"} # 4 hints
- ignore: {name: "Eta reduce"} # 30 hints
- ignore: {name: "Evaluate"} # 1 hint
- ignore: {name: "Fix pragma markup"} # 38 hints
- ignore: {name: "Functor law"} # 3 hints
- ignore: {name: "Move brackets to avoid $"} # 8 hints
- ignore: {name: "Redundant $"} # 20 hints
- ignore: {name: "Redundant <$>"} # 29 hints
- ignore: {name: "Redundant bang pattern"} # 33 hints
- ignore: {name: "Redundant bracket"} # 198 hints
- ignore: {name: "Redundant flip"} # 1 hint
- ignore: {name: "Redundant if"} # 1 hint
- ignore: {name: "Unused LANGUAGE pragma"} # 29 hints
- ignore: {name: "Use $>"} # 7 hints
- ignore: {name: "Use ++"} # 1 hint
- ignore: {name: "Use <$"} # 2 hints
- ignore: {name: "Use <$>"} # 10 hints
- ignore: {name: "Use camelCase"} # 2 hints
- ignore: {name: "Use concatMap"} # 3 hints
- ignore: {name: "Use const"} # 1 hint
- ignore: {name: "Use first"} # 1 hint
- ignore: {name: "Use fold"} # 1 hint
- ignore: {name: "Use gets"} # 9 hints
- ignore: {name: "Use guards"} # 3 hints
- ignore: {name: "Use infix"} # 3 hints
- ignore: {name: "Use map once"} # 1 hint
- ignore: {name: "Use mapMaybe"} # 4 hints
- ignore: {name: "Use maybe"} # 7 hints
- ignore: {name: "Use record patterns"} # 5 hints
- ignore: {name: "Use second"} # 1 hint
- ignore: {name: "Use section"} # 3 hints
- ignore: {name: "Use tuple-section"} # 1 hint
