# The following are kept for usability and style sake
- ignore: {name: "Avoid lambda"} # 5 hints
- ignore: {name: "Eta reduce"} # 35 hints
- ignore: {name: "Use $>"} # 7 hints
- ignore: {name: "Use <$"} # 0 hints
- ignore: {name: "Use infix"} # 3 hints

# Warnings currently triggered by your code
- ignore: {name: "Avoid reverse"} # 1 hint
- ignore: {name: "Functor law"} # 2 hints
- ignore: {name: "Fuse concatMap/<$>"} # 1 hint
- ignore: {name: "Fuse foldr/<$>"} # 2 hints
- ignore: {name: "Move mapMaybe"} # 1 hint
- ignore: {name: "Unused LANGUAGE pragma"} # 1 hint
- ignore: {name: "Use map with tuple-section"} # 1 hint
