
resolver: lts-18.27
allow-newer: true

flags:
  liquid-fixpoint:
    devel: true 

packages:
- '.'

extra-deps:
- hashable-1.3.5.0
- rest-rewrite-0.3.0
- git: https://github.com/tweag/smtlib-backends
  commit: d309d6cc09298cd575020c791b7affa7e0098f1f
- git: https://github.com/tweag/smtlib-backends
  commit: d309d6cc09298cd575020c791b7affa7e0098f1f
  subdir: smtlib-backends-z3
- git: https://github.com/tweag/smtlib-backends
  commit: d309d6cc09298cd575020c791b7affa7e0098f1f
  subdir: smtlib-backends-process
- typed-process-0.2.10.1@sha256:cc35b76f2ce32c708cb2f68a1c4f661a8138196d958e34a2f214208333a73f46,2070


nix:
  packages: [z3]
