
resolver: lts-18.14
compiler: ghc-8.10.7
# compiler: ghc-8.8.4
# compiler: ghc-8.6.5
allow-newer: true

# resolver: lts-14.0

flags:
  liquid-fixpoint:
    devel: true 

packages:
- '.'


extra-deps:
- hashable-1.3.0.0
- git: https://github.com/zgrannan/rest
  commit: 2833a743c310747eee1accba2a5bf0b5338e7bb6

nix:
  shell-file: shell-stack.nix
  path: ["nixpkgs=./nixpkgs.nix"]
