
resolver: nightly-2023-11-27

flags:
  liquid-fixpoint:
    devel: true 
    link-z3-as-a-library: true

packages:
- '.'

extra-deps:
- smtlib-backends-0.3@rev:1
- smtlib-backends-process-0.3@rev:1
- smtlib-backends-z3-0.3@rev:1

nix:
  packages: [z3]
