
resolver: lts-20.1
allow-newer: true

flags:
  liquid-fixpoint:
    devel: true 

packages:
- '.'

extra-deps:
- hashable-1.4.2.0
- rest-rewrite-0.4.1
- smtlib-backends-0.3
- smtlib-backends-z3-0.3
- smtlib-backends-process-0.3

nix:
  packages: [z3]
