
resolver: nightly-2023-11-27

flags:
  liquid-fixpoint:
    devel: true 
#   Don't enable z3 linking by default
#   Most of the time, devs don't care about it and it demands the
#   z3 library to be at the linker's reach.
#   link-z3-as-a-library: true

packages:
- '.'

extra-deps:
- smtlib-backends-0.3@rev:1
- smtlib-backends-process-0.3@rev:1
- smtlib-backends-z3-0.3@rev:1

nix:
  packages: [z3]
