---
version: 2.0

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01 # recommended linux image - includes Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1
    docker:
      - image: fpco/stack-build:lts-15.4
    steps:
      - add_ssh_keys
      - run: 
          name: Install z3 
          command: |
            wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.7/z3-4.8.7-x64-ubuntu-16.04.zip
            unzip z3-4.8.7-x64-ubuntu-16.04.zip
            rm -f z3-4.8.7-x64-ubuntu-16.04.zip
            cp z3-4.8.7-x64-ubuntu-16.04/bin/libz3.a /usr/local/lib
            cp z3-4.8.7-x64-ubuntu-16.04/bin/z3 /usr/local/bin
            cp z3-4.8.7-x64-ubuntu-16.04/include/* /usr/local/include
            rm -rf z3-4.8.7-x64-ubuntu-16.04
            echo $PATH
            z3 --version

      - checkout
      - restore_cache:
          keys:
            - stack-{{ checksum "stack.yaml" }}
      - run:
          name: Dependencies
          command: |
            stack setup
            stack build liquid-fixpoint --only-dependencies --test --no-run-tests
      - save_cache:
          key: stack-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Compile
          command : |
            stack build liquid-fixpoint --flag liquid-fixpoint:devel
            stack build liquid-fixpoint --flag liquid-fixpoint:devel --test --no-run-tests
      - run:
          name: Test
          command: |
            stack clean
            echo $PATH
            z3 --version
            mkdir -p /tmp/junit
            stack test liquid-fixpoint:test --flag liquid-fixpoint:devel --test-arguments="--xml=/tmp/junit/main-test-results.xml":
            stack haddock
            stack sdist
            # mkdir -p $CIRCLE_TEST_REPORTS/tasty
            # cp -r tests/logs/cur $CIRCLE_TEST_REPORTS/tasty/log
      - run:
          name: Dist
          command: stack sdist
