name: cabal

on:
  push:
  pull_request:

jobs:
  build:
    name: ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cabal: ["3.6"]
        ghc:
          - "8.10.7"
          - "9.2.3"

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup GHC and cabal-install
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
          restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

      - uses: pavpanchekha/setup-z3@1.2.2
        name: setup z3
        with:
          version: "4.8.7"

      - name: update
        run: |
          cabal update

      - name: build
        run: cabal build all --enable-tests

      - name: test
        run: cabal test all --test-show-details=direct --test-option="--color=always"