name: hlint

on:
  push:
    branches:
      - develop
  pull_request:

jobs:
  build:
    name: hlint-3.8
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4

    - uses: haskell-actions/hlint-setup@v2
      name: Set up HLint
      with:
        version: "3.8"

    - uses: haskell-actions/hlint-run@v2
      name: hlint
      with:
        path: '["src/", "tests/", "unix/", "win/"]'
        fail-on: suggestion
